//go:generate stringer -type Currency
package asset

// Code generated by asset
// DO NOT EDIT

const (
	XICN Currency = iota
	XXDG
	XZEC
	ZCAD
	DASH
	XDAO
	ZGBP
	ZJPY
	ZKRW
	BCH
	KFEE
	XXMR
	XXRP
	ZEUR
	ZUSD
	USDT
	XLTC
	XMLN
	XXVN
	XETC
	XETH
	XNMC
	XXBT
	XXLM
	EOS
	GNO
	XREP
)

type Currency int

var validCurrencies = []Currency{
	XICN,
	XXDG,
	XZEC,
	ZCAD,
	DASH,
	XDAO,
	ZGBP,
	ZJPY,
	ZKRW,
	BCH,
	KFEE,
	XXMR,
	XXRP,
	ZEUR,
	ZUSD,
	USDT,
	XLTC,
	XMLN,
	XXVN,
	XETC,
	XETH,
	XNMC,
	XXBT,
	XXLM,
	EOS,
	GNO,
	XREP,
}
