// Code generated by "stringer -type Currency"; DO NOT EDIT.

package asset

import "fmt"

const _Currency_name = "KFEEXDAOXNMCXXDGDASHEOSXXBTXXLMXREPBCHZJPYXXMRZCADZGBPXETHXMLNGNOXICNXLTCZUSDUSDTXETCXXRPXXVNXZECZEURZKRW"

var _Currency_index = [...]uint8{0, 4, 8, 12, 16, 20, 23, 27, 31, 35, 38, 42, 46, 50, 54, 58, 62, 65, 69, 73, 77, 81, 85, 89, 93, 97, 101, 105}

func (i Currency) String() string {
	if i < 0 || i >= Currency(len(_Currency_index)-1) {
		return fmt.Sprintf("Currency(%d)", i)
	}
	return _Currency_name[_Currency_index[i]:_Currency_index[i+1]]
}
