// Code generated by "stringer -type Currency"; DO NOT EDIT.

package asset

import "fmt"

const _Currency_name = "XICNXXDGXZECZCADDASHXDAOZGBPZJPYZKRWBCHKFEEXXMRXXRPZEURZUSDUSDTXLTCXMLNXXVNXETCXETHXNMCXXBTXXLMEOSGNOXREP"

var _Currency_index = [...]uint8{0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79, 83, 87, 91, 95, 98, 101, 105}

func (i Currency) String() string {
	if i < 0 || i >= Currency(len(_Currency_index)-1) {
		return fmt.Sprintf("Currency(%d)", i)
	}
	return _Currency_name[_Currency_index[i]:_Currency_index[i+1]]
}
