// Code generated by "stringer -type Currency"; DO NOT EDIT.

package asset

import "fmt"

const _Currency_name = "EOSXXBTXXRPGNOXICNXMLNZJPYXZECZCADZGBPXETCXLTCXNMCXXLMUSDTXREPZEURBCHDASHZUSDZKRWXXDGXXMRKFEEXDAOXETHXXVN"

var _Currency_index = [...]uint8{0, 3, 7, 11, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 69, 73, 77, 81, 85, 89, 93, 97, 101, 105}

func (i Currency) String() string {
	if i < 0 || i >= Currency(len(_Currency_index)-1) {
		return fmt.Sprintf("Currency(%d)", i)
	}
	return _Currency_name[_Currency_index[i]:_Currency_index[i+1]]
}
