//go:generate stringer -type AssetPair
package pairs

// Code generated by pairs
// DO NOT EDIT

const (
{{- range $k, $v := .}}
{{- if eq $k 0 }}
{{$v}} AssetPair = iota
{{else -}}
{{$v}}
{{end -}}

{{- end}}
)

type AssetPair int

var validPairs = []AssetPair{
{{- range $k, $v := .}}
{{$v}},
{{- end}}
}